#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\Service\LocalConfig;
use Minicli\App;
use Minicli\Exception\CommandNotFoundException;


$localConfig = LocalConfig::loadFromFile();

$app = new App([
    'app_path' => __DIR__ . '/app/Command',

    /**
     * From local config file
     */
    'BENTODB_API_KEY' => $localConfig['BENTODB_API_KEY'] ?? null,
    'BENTODB_API_URL' => $localConfig['BENTODB_API_URL'] ?? 'https://www.bentodb.com/api',
]);

$app->setSignature("BentoDB CLI                      
                       :++:                       
                    -*@@@@@@*-                    
                .=..=#@@@@@@%+:.-:                
             -*%@@@@*-.-**-.:+%@@@@*-             
         .. +%@@@@@@@%+ .. =#@@@@@@@%+. :         
      :+%@@%+:.=#@#=.:+%@@%+-.-*@#=..=#@@@*-      
    -%@@@@@@@@%:   :#@@@@@@@@%-   .#@@@@@@@@@=    
   *=..=#@@#=.:+%@%+:.=#@@#+:.=#@%+:.-*@@%+:.=#   
   %@@%*-.  +@@@@@@@@@+    =%@@@@@@@@*. .:+%@@@   
   %@@@@@ .=.:+%@@@%+:.=##=:.=#@@@%+:.-- @@@@@@   
   *@@@@@ :@@%+-.-.:+%@@@@@@@*- -.:+%@@= @@@@@#   
     :+%@ :@@@@@# :.:+%@@@@@*-.- +@@@@@= @@*-     
        . :@@@@@# *@%+:.==.:=#@% +@@@@@= .        
            :+%@# *@@@@@: @@@@@% +@@*-            
               .- *@@@@@- @@@@@% ::               
                   -*@@@- @@@*-                   
                      .=: +:                      

./bentodb <command> [options]

./bentodb configure
./bentodb create");

try {
    $app->runCommand($argv);
} catch (CommandNotFoundException $e) {
    echo 'An error occurred running the command: ',  $e->getMessage(), "\n";
}
